### ISSUE TITLE
Can’t get unread entries of a feed directly

### ISSUE THREAD

**Issue by kaiserkiwi** [feedbin/feedbin-api#15]
The URL https://api.feedbin.com/v2/feeds/{id}/entries.json gives me all the entries from a specific feed, but if I try https://api.feedbin.com/v2/feeds/{id}/unread_entries.json I get a 404. Why? It would be much easier, if I just could get the unread entries for a specific feed.

**Comment by cathalgarvey** [comment]
Can I bump this one, please? It seems a strange thing for the API not to support. Is there a more idiomatic way to get unread messages on a per-feed basis?

Or does one have to collect _all_ unreads, and then issue requests to find out which feeds they belong to? That seems clunky.

**Comment by benubois** [comment]
> Is there a more idiomatic way to get unread messages on a per-feed basis?

Try:

```bash
curl --request GET --user "example@example.com:password" https://api.feedbin.com/v2/feeds/FEED_ID/entries.json?read=false
```

Looks like it wasn't documented.

**Comment by benubois** [comment]
If you are trying to get unread articles for all feeds though, it is much better to use the [unread entries](https://github.com/feedbin/feedbin-api/blob/master/content/unread-entries.md) api, then request the entries by id instead of looping through all your subscriptions.

```bash
curl --request GET --user "example@example.com:password" https://api.feedbin.com/v2/unread_entries.json
```

```json
[321,321]
```

```bash
curl --request GET --user "example@example.com:password" https://api.feedbin.com/v2/entries.json?ids=123,321
```

**Comment by cathalgarvey** [comment]
This is great, thanks for the quick feedback! :)
