### ISSUE TITLE
Unread count in subscriptions

### ISSUE THREAD

**Issue by kaiserkiwi** [feedbin/feedbin-api#16]
I think, there should be an unread count, in the subscriptions-JSON. So next to id (what is the use of), created_at, feed_id, title, feed_url and site_url it would be nice, if there were a unread_count starting with 0 if it is empty.
This would make the JavaScript-Development (Windows Phone) much easier.

**Comment by A973C** [comment]
Hi @benubois 
Is there a way to retrieve the unread entries count by subscription feeds like on the website, please?
