### ISSUE TITLE
Getting entries by tag

### ISSUE THREAD

**Issue by karllhughes** [feedbin/feedbin-api#19]
Just curious, is there a way to get all entries by a specific tag or tag id?

I use tags to create categories for my feeds, so I'd like to only get posts one tag at a time.

Thanks!

**Comment by benubois** [comment]
Hi @karllhughes,

There isn't a way to do this currently. The API is designed more from a full-sync perspective so it doesn't have a lot of convenience end-points. 

One approach would be to collect the feed_ids in a tag from [Taggings](https://github.com/feedbin/feedbin-api/blob/master/content/taggings.md), then get all of the entries in each of the feeds from the `/v2/feeds/feed_id/entries.json` endpoint.

Please let me know if you have questions about this.

Thanks!

**Comment by karllhughes** [comment]
@benubois thanks! Your approach is basically what I ended up doing and it seems to work fine. Just figured I would ask about this endpoint in case I missed it.
