### ISSUE TITLE
cleaned up HTML through the API?

### ISSUE THREAD

**Issue by tieguy** [feedbin/feedbin-api#24]
It'd be nice if the API offered a way to get the Mercury-ized HTML of the body as Feedbin sees it rather than just the raw entry. I can obviously do this myself to some extent, but to be frank the old ports of the original Readability code are showing their age :/

(Totally understand if this isn't possible under your terms with Mercury.)

**Comment by benubois** [comment]
Hi!

Mercury is completely free and available for anyone to use. https://mercury.postlight.com/web-parser/

You can just pass the url you get from the Feedbin API to the Mercury API. 

Thanks!

Ben

**Comment by tieguy** [comment]
Yeah, that does the job but I was hoping to rely mostly on services I can pay for and so actually rely on :) No biggie, though.
