### ISSUE TITLE
extracted_content_url

### ISSUE THREAD

**Issue by sjoonk** [feedbin/feedbin-api#27]
This morning, I found a new field named 'extracted_content_url' from Feedbin's entry endpoint call.
It's not documented yet.

What's is this field?
Is it temporary or permanent?
What's the purpose of this field?

Can i use this field safely?

**Comment by sjoonk** [comment]
I found the answer.
https://feedbin.com/blog/2019/03/11/the-future-of-full-content/

Thank you and happy 6th birthday!!

**Comment by benubois** [comment]
Wow! I'm amazed you noticed this almost immediately. Thanks for the reminder to update the docs.
