### ISSUE TITLE
Feed title changes not reflected in the API

### ISSUE THREAD

**Issue by djl** [feedbin/feedbin-api#28]
While playing around with the API I noticed that changes to a feed's title are not carried through to the API. Here's an example of what the API returns (with sensitive data redacted):

    {
      'feed_url': 'https://example.com/feed.xml',
      'id': 12345,
      'site_url': 'https://example.com,
      'title': 'The Original Title'
    }

And here's what I'd expect:

    {
      'feed_url': 'https://example.com/feed.xml',
      'id': 12345,
      'site_url': 'https://example.com,
      'title': 'Something completely different'
    }

Is this intended? If so, is there a way to get the altered feed title?

**Comment by benubois** [comment]
Hi @djl,

Sorry for the trouble! In general it's very helpful if you could include the request and response. In this example I'm not sure what API you're calling.

However, if you're requesting `/v2/feed.json`, then that is as expected. The `feeds` API shows you the feed details including the _original_ title. The [`/v2/subscriptions.json`](https://api.feedbin.com/v2/subscriptions.json) API shows the subscription details including the new title if it has been renamed.

**Comment by djl** [comment]
> In general it's very helpful if you could include the request and response. In this example I'm not sure what API you're calling.

Hmm. My nice `curl` examples went missing somewhere between my brain and keyboard :(

> However, if you're requesting /v2/feed.json, then that is as expected. The feeds API shows you the feed details including the original title. The /v2/subscriptions.json API shows the subscription details including the new title if it has been renamed.

Aha! That's exactly what I needed. Thanks!

My problem was that I didn't pick up on the difference between a feed and a subscription as the current docs treat them almost identically. Maybe the differences could be more thoroughly explained?
