### ISSUE TITLE
Feature Request: Remove Pagination when fetching Saved Searches' entry IDs only.

### ISSUE THREAD

**Issue by kunalsood** [feedbin/feedbin-api#56]
Please consider removing the requirement to paginate when getting a Saved Search's entry IDs using eg. `GET /v2/saved_searches/1.json` with `include_entries:` set to `false`.

In my testing, a simple saved search has more than 100k result count, requiring my offline-first client to send more than 1000 requests to just get entry IDs of entries I already have locally cached.

**Comment by benubois** [comment]
This should be improved now. 

The intent with the saved_searches API is not to be `exhaustive`. I don't think 100k results would have much utility.

The API previously limited the number of result pages to 5, but the counts and pages headers did not match this.

The new system will return the most recent/top 1,000 ids with no pages, unless `include_entries=true` is set.

Thanks!
