### ISSUE TITLE
[feedbin api feedback] Confusing extract-full-content return value

### ISSUE THREAD

**Issue by chyroc** [feedbin/feedbin-api#60]
Hello, feedbin company, I want to report an api-related issue

About extract-full-content api: https://github.com/feedbin/feedbin-api/blob/master/content/extract-full-content.md

I guess this api is a working method similar to asynchronous tasks. There is a working/pending similar working state for a period of time. After the processing is completed, the real api result is returned.

But when you were implementing this api, when the asynchronous task was being processed, you returned an error: {"error":true,"messages":"User does not exist: chyroc@qq.com."}

This is not correct, you should return: the task is being processed in an intermediate state.

Thank you, I hope you can correct the return value processing of this api.

my code:

![image](https://user-images.githubusercontent.com/15604894/134790899-b4728133-ab19-4e6c-9636-41b5ae2a16f0.png)

**Comment by benubois** [comment]
Hi @chyroc,

It's not an async api. The extract service is only available to consumer apps that sync with feedbin.com. See the note at the top:

> If you have a native app that supports Feedbin, you can use Feedbin's full content service.

It is possible to get a cached article without an account, which is probably why you occasionally get a result.

Thanks!
