### ISSUE TITLE
Count unread entries

### ISSUE THREAD

**Issue by A973C** [feedbin/feedbin-api#63]
Hi @benubois 

Could you please tell me how to get unread entries counter, please?

API documentation don't explain that part.

Thank you for your help and for your great work!

**Comment by A973C** [comment]
Ping @benubois

**Comment by A973C** [comment]
Ping @benubois

**Comment by A973C** [comment]
Hi @benubois 

Could you please give me an answer? There's no customer support at Feedbin??

**Comment by benubois** [comment]
Hi,

The [Unread entries](https://github.com/feedbin/feedbin-api/blob/master/content/unread-entries.md) endpoint returns an array of unread entry ids, so the count of unread entries is equal to the length of the array.

In general no support is available for how to accomplish things with the API as this is highly dependent on the language you're using.

Ben
