### ISSUE TITLE
Retrieve icon of individual subscription

### ISSUE THREAD

**Issue by logancgarcia** [feedbin/feedbin-api#69]
Currently, the `/v2/icons` endpoint does not support grabbing an individual icon for a feed. This may be useful in the case of third party feed readers that want an endpoint to grab an individual icon. I  can think of three possibilities to solve this:

1. Allow to append a subscription id to the `/v2/icons` endpoint, so that an individual icon could be obtained by calling, for example, `/v2/icons/525.json`
2. Include an `icon` field for a subscription response, so that a call to, for example, `/v2/subscriptions/525.json`, would return its regular payload in addition to the aforementioned icon field
3. Potentially create a new endpoint to retrieve this information, as the `/v2/icons` endpoint may not be the intended place for this information (as outlined in https://github.com/feedbin/feedbin-api/issues/52, which outlines the concern that not all icons for subscriptions are populated)

**Comment by benubois** [comment]
Hi @logancgarcia,

The existing API should work just fine for this as you can match the hostname to the item you need in the icons array. 

Thanks!

**Comment by gabrielittner** [comment]
@benubois the exception to that is when the subscription has a different icon and does not use the host icon, for example for YouTube.
