### ISSUE TITLE
Document the maximum number of entries that can be retrieve with the `id` query parameter

### ISSUE THREAD

**Issue by sesh** [feedbin/feedbin-api#70]
I have a script that takes starred entry ids, then uses the `id` param on the `/entries` API to get those entries.

It started failing when I hit 100 starred entries on my account.

I'm happy to update the docs in a PR if someone from Feedbin confirms the limit is 100.

**Comment by benubois** [comment]
Hi @sesh,

The limit is stated in the [Pagination section](https://github.com/feedbin/feedbin-api#pagination), however I’d be happy to accept a PR to put it where you expected to find it. 

Thanks!

![IMG_4539](https://github.com/feedbin/feedbin-api/assets/133809/50e8580c-eb31-48c9-b934-a85939bc4c01)

**Comment by sesh** [comment]
Thanks for the quick response @benubois. Admittedly, I ran straight to the entries page then tarted experimenting without even looking for a pagination page.

In the case of the `/entries.json?ids=1,2,3,4,5` request, the response when you request over 100 items is actually a 400, rather than a paginated response. I don't really want to open a can of worms by starting to describe limits outside of the pagination page, but this might justify it for this endpoint?
